# Generated by Django 3.0 on 2020-05-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0006_merge_20200503_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
