# Generated by Django 3.0.4 on 2020-04-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorilibri',
            options={'verbose_name_plural': 'Autorilibri'},
        ),
        migrations.AlterModelOptions(
            name='codicedewey',
            options={'verbose_name_plural': 'CodiciDewey'},
        ),
        migrations.AlterModelOptions(
            name='collocazione',
            options={'verbose_name_plural': 'Collocazioni'},
        ),
        migrations.AlterModelOptions(
            name='editori',
            options={'verbose_name_plural': 'Editori'},
        ),
        migrations.AlterModelOptions(
            name='libri',
            options={'verbose_name_plural': 'Libri'},
        ),
        migrations.AlterModelOptions(
            name='prestiti',
            options={'verbose_name_plural': 'Prestiti'},
        ),
        migrations.AlterModelOptions(
            name='scarichi',
            options={'verbose_name_plural': 'Scarichi'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'Sedi'},
        ),
        migrations.AlterModelOptions(
            name='stato',
            options={'verbose_name_plural': 'Stati'},
        ),
        migrations.AlterModelOptions(
            name='utenti',
            options={'verbose_name_plural': 'Utenti'},
        ),
    ]
