# Generated by Django 3.0 on 2020-05-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0008_libri_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestiti',
            name='dataprelievo',
            field=models.DateTimeField(auto_now_add=True, db_column='dataPrelievo'),
        ),
    ]
