# Generated by Django 3.0 on 2020-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0009_auto_20200504_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='inprestito',
            field=models.BooleanField(db_column='InPrestito', default=False),
        ),
    ]
