# Generated by Django 3.0.4 on 2020-05-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
