# Generated by Django 3.0 on 2020-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_auto_20200408_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Libri',
            },
        ),
        migrations.DeleteModel(
            name='Libri',
        ),
    ]
