# Generated by Django 3.0 on 2020-04-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_auto_20200409_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idLibro',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
