# Generated by Django 3.0 on 2020-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_auto_20200409_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autore',
        ),
        migrations.AddField(
            model_name='libro',
            name='Descrizione',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='IdCollocazione',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='IdSede',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='IdStato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='InPrestito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='Pagine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='dataAcquisto',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='AnnoPubblicazione',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Dewey',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='IdEdi',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Isbn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Nedizione',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Titolo',
            field=models.TextField(default=''),
        ),
    ]
