# Generated by Django 3.0 on 2020-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_codicedewey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorilibri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlibro', models.TextField(blank=True, db_column='IdLibro', null=True)),
                ('idautore', models.TextField(blank=True, db_column='IdAutore', null=True)),
            ],
            options={
                'db_table': 'AutoriLibri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collocazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcol', models.TextField(blank=True, db_column='IdCol', null=True)),
                ('collocazione', models.TextField(blank=True, db_column='Collocazione', null=True)),
            ],
            options={
                'db_table': 'Collocazione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideditore', models.TextField(blank=True, db_column='IdEditore', null=True)),
                ('editore', models.TextField(blank=True, db_column='Editore', null=True)),
            ],
            options={
                'db_table': 'Editori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlibro', models.TextField(blank=True, db_column='IdLibro', null=True)),
                ('dewey', models.TextField(blank=True, db_column='Dewey', null=True)),
                ('titolo', models.TextField(blank=True, db_column='Titolo', null=True)),
                ('isbn', models.TextField(blank=True, db_column='Isbn', null=True)),
                ('idedi', models.TextField(blank=True, db_column='IdEdi', null=True)),
                ('nedizione', models.TextField(blank=True, db_column='Nedizione', null=True)),
                ('annopubblicazione', models.TextField(blank=True, db_column='AnnoPubblicazione', null=True)),
                ('prezzo', models.TextField(blank=True, db_column='Prezzo', null=True)),
                ('dataacquisto', models.TextField(blank=True, db_column='dataAcquisto', null=True)),
                ('descrizione', models.TextField(blank=True, db_column='Descrizione', null=True)),
                ('pagine', models.TextField(blank=True, db_column='Pagine', null=True)),
                ('idcollocazione', models.TextField(blank=True, db_column='IdCollocazione', null=True)),
                ('idsede', models.TextField(blank=True, db_column='IdSede', null=True)),
                ('inprestito', models.TextField(blank=True, db_column='InPrestito', null=True)),
                ('idstato', models.TextField(blank=True, db_column='IdStato', null=True)),
            ],
            options={
                'db_table': 'Libri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprestito', models.TextField(blank=True, db_column='IdPrestito', null=True)),
                ('idlibro', models.TextField(blank=True, db_column='IdLibro', null=True)),
                ('idutente', models.TextField(blank=True, db_column='IdUtente', null=True)),
                ('dataprelievo', models.TextField(blank=True, db_column='dataPrelievo', null=True)),
                ('datarestituzione', models.TextField(blank=True, db_column='dataRestituzione', null=True)),
            ],
            options={
                'db_table': 'Prestiti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scarichi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlibro', models.TextField(blank=True, db_column='IdLibro', null=True)),
                ('data', models.TextField(blank=True, db_column='Data', null=True)),
                ('motivo', models.TextField(blank=True, db_column='Motivo', null=True)),
            ],
            options={
                'db_table': 'Scarichi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsede', models.TextField(blank=True, db_column='IdSede', null=True)),
                ('sede', models.TextField(blank=True, db_column='Sede', null=True)),
            ],
            options={
                'db_table': 'Sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstato', models.TextField(blank=True, db_column='IdStato', null=True)),
                ('stato', models.TextField(blank=True, db_column='Stato', null=True)),
            ],
            options={
                'db_table': 'Stato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idutente', models.TextField(blank=True, db_column='IdUtente', null=True)),
                ('cognomenome', models.TextField(blank=True, db_column='CognomeNome', null=True)),
                ('classe', models.TextField(blank=True, db_column='Classe', null=True)),
            ],
            options={
                'db_table': 'Utenti',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AlterModelOptions(
            name='autori',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='codicedewey',
            options={'managed': False},
        ),
    ]
