# Generated by Django 3.0 on 2020-04-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0009_auto_20200411_1826'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autori',
            table='Autori',
        ),
        migrations.AlterModelTable(
            name='codicedewey',
            table='CodiceDewey',
        ),
    ]
