# Generated by Django 3.0 on 2020-04-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0010_auto_20200411_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autori',
            options={'verbose_name': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='autorilibri',
            options={},
        ),
        migrations.AlterModelOptions(
            name='codicedewey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collocazione',
            options={},
        ),
        migrations.AlterModelOptions(
            name='editori',
            options={},
        ),
        migrations.AlterModelOptions(
            name='libri',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prestiti',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scarichi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utenti',
            options={},
        ),
    ]
