# Generated by Django 3.0 on 2020-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0011_auto_20200411_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autori',
            options={'verbose_name_plural': 'Autori'},
        ),
        migrations.RemoveField(
            model_name='autori',
            name='CognomeNome',
        ),
        migrations.RemoveField(
            model_name='autori',
            name='idAutore',
        ),
        migrations.RemoveField(
            model_name='codicedewey',
            name='Argomento',
        ),
        migrations.RemoveField(
            model_name='codicedewey',
            name='Dew',
        ),
        migrations.RemoveField(
            model_name='codicedewey',
            name='idDew',
        ),
        migrations.RemoveField(
            model_name='libri',
            name='id',
        ),
        migrations.AddField(
            model_name='autori',
            name='cognomenome',
            field=models.TextField(blank=True, db_column='CognomeNome', null=True),
        ),
        migrations.AddField(
            model_name='autori',
            name='idautore',
            field=models.TextField(db_column='IdAutore', default=-1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='codicedewey',
            name='argomento',
            field=models.TextField(blank=True, db_column='Argomento', null=True),
        ),
        migrations.AddField(
            model_name='codicedewey',
            name='dew',
            field=models.TextField(blank=True, db_column='Dew', null=True),
        ),
        migrations.AddField(
            model_name='codicedewey',
            name='iddew',
            field=models.TextField(db_column='IdDew', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libri',
            name='idlibro',
            field=models.TextField(db_column='IdLibro', primary_key=True, serialize=False),
        ),
    ]
