# Generated by Django 3.0 on 2020-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='annopubblicazione',
            field=models.CharField(blank=True, db_column='AnnoPubblicazione', max_length=4, null=True),
        ),
    ]
