# Generated by Django 3.0 on 2020-04-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0002_auto_20200415_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='idcollocazione',
            field=models.ForeignKey(db_column='IdCollocazione', default='[Vuoto]', on_delete=django.db.models.deletion.SET_DEFAULT, to='libri.Collocazione'),
        ),
    ]
