# Generated by Django 3.0 on 2020-05-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0003_auto_20200415_1757'),
        ('libri', '0005_user'),
    ]

    operations = [
    ]
