# Generated by Django 3.0 on 2020-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='libri',
            name='immagine',
            field=models.ImageField(blank=True, db_column='Immagine', null=True, upload_to=''),
        ),
    ]
